
import "./globals.css";
import { UnitProvider } from "./contexts/unitContext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`bg-[#02012b]`}
      >
        <UnitProvider>
          {children}
        </UnitProvider>
        
      </body>
    </html>
  );
}
